/** Glosario y ayuda en lenguaje simple (RF-44, RF-45). Todo el texto de ayuda vive acá. */

export type GlossaryCategory = "Mercado" | "Renta fija" | "Acciones y CEDEARs" | "Dólar" | "Gráficos";

export interface GlossaryEntry {
  id: string;
  term: string;
  category: GlossaryCategory;
  /** Una frase: qué es. */
  short: string;
  /** Cómo se lee el dato. */
  read: string;
  /** Por qué importa. */
  why: string;
  aliases?: string[];
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    id: "cedear",
    term: "CEDEAR",
    category: "Acciones y CEDEARs",
    short: "Certificado que representa una fracción de una acción extranjera y cotiza en BYMA.",
    read: "Cada CEDEAR equivale a una parte de la acción original según su ratio de conversión. Su precio en pesos sale del precio en dólares de la acción, el ratio y el tipo de cambio.",
    why: "Permite exponerse a empresas de EE.UU. desde una cuenta local. Su precio se mueve por la acción y también por el dólar implícito.",
    aliases: ["cedears", "certificado de depósito argentino"],
  },
  {
    id: "ratio",
    term: "Ratio de conversión",
    category: "Acciones y CEDEARs",
    short: "Cuántos CEDEARs hacen falta para igualar una acción del exterior.",
    read: "Un ratio 10:1 significa que 10 CEDEARs equivalen a 1 acción. Precio del CEDEAR ≈ precio de la acción × tipo de cambio ÷ ratio.",
    why: "Sin el ratio no se puede comparar el CEDEAR con su acción ni calcular el dólar implícito.",
    aliases: ["ratio", "paridad cedear"],
  },
  {
    id: "accion",
    term: "Acción",
    category: "Acciones y CEDEARs",
    short: "Parte del capital de una empresa. Quien la tiene es dueño de una fracción.",
    read: "El precio sube o baja según lo que el mercado espera de las ganancias futuras de la empresa.",
    why: "Puede dar ganancia por suba de precio y por dividendos, pero no tiene rendimiento asegurado y puede perder valor.",
    aliases: ["acciones", "equity"],
  },
  {
    id: "bono",
    term: "Bono",
    category: "Renta fija",
    short: "Título de deuda: prestás plata a un emisor que se compromete a devolverla con intereses.",
    read: "Se define por su cupón (interés), su vencimiento y su moneda de pago. El precio se expresa cada 100 nominales.",
    why: "Los pagos son conocidos de antemano, pero depende de que el emisor pague. Si el precio cae, el rendimiento (TIR) sube.",
    aliases: ["bonos", "soberano", "renta fija"],
  },
  {
    id: "on",
    term: "Obligación negociable",
    category: "Renta fija",
    short: "Bono emitido por una empresa privada en lugar del Estado.",
    read: "Igual que un bono: cupón, vencimiento y moneda. Suele pagar más que un bono del Estado de plazo similar.",
    why: "El riesgo depende de la empresa emisora: si no puede pagar, el inversor pierde parte o todo.",
    aliases: ["on", "obligaciones negociables", "corporativo"],
  },
  {
    id: "letra",
    term: "Letra",
    category: "Renta fija",
    short: "Título de deuda del Estado de corto plazo, que se paga de una sola vez al vencimiento.",
    read: "Se compra con descuento y al vencimiento se cobra el valor completo. La diferencia es la ganancia.",
    why: "Sirve para colocar pesos a plazos cortos con pagos conocidos de antemano.",
    aliases: ["letras", "lecap", "letes"],
  },
  {
    id: "fci",
    term: "FCI",
    category: "Mercado",
    short: "Fondo común de inversión: junta plata de muchos inversores y la administra un profesional.",
    read: "Se compra por cuotapartes. El valor de la cuotaparte se actualiza cada día según los activos del fondo.",
    why: "Diversifica con poca plata. Cobra comisiones y el rendimiento depende de qué compre el fondo.",
    aliases: ["fondo común de inversión", "fondos", "cuotaparte"],
  },
  {
    id: "per",
    term: "PER (P/E)",
    category: "Acciones y CEDEARs",
    short: "Cuántos años de ganancias actuales hacen falta para pagar el precio de la acción.",
    read: "PER = precio ÷ ganancia por acción. Un PER de 20 dice que pagás 20 veces lo que la empresa gana en un año.",
    why: "Sirve para comparar si una acción está cara o barata frente a su propia historia y a empresas parecidas. Un PER bajo no siempre es una ganga.",
    aliases: ["p/e", "price earnings", "precio ganancia"],
  },
  {
    id: "eps",
    term: "Ganancia por acción (EPS)",
    category: "Acciones y CEDEARs",
    short: "La ganancia de la empresa dividida por la cantidad de acciones.",
    read: "Si el EPS crece año a año, la empresa gana más por cada acción que existe.",
    why: "Es la base del PER y muestra si el negocio mejora o empeora.",
    aliases: ["eps", "utilidad por acción"],
  },
  {
    id: "dividend-yield",
    term: "Rendimiento por dividendo",
    category: "Acciones y CEDEARs",
    short: "Lo que la empresa paga por año en dividendos, como porcentaje del precio.",
    read: "Un 3 % significa que por cada 100 invertidos la empresa reparte 3 al año.",
    why: "Es un ingreso aparte de la suba de precio. Un rendimiento muy alto puede indicar que el precio cayó por problemas.",
    aliases: ["dividendos", "dividend yield", "yield"],
  },
  {
    id: "beta",
    term: "Beta",
    category: "Acciones y CEDEARs",
    short: "Qué tanto se mueve una acción respecto del mercado.",
    read: "Beta 1 se mueve igual que el mercado. Mayor a 1 se mueve más; menor a 1, menos.",
    why: "Una acción con beta alto sube más en los buenos momentos y cae más en los malos.",
    aliases: ["volatilidad"],
  },
  {
    id: "market-cap",
    term: "Capitalización de mercado",
    category: "Acciones y CEDEARs",
    short: "El valor total de una empresa en bolsa: precio × cantidad de acciones.",
    read: "Se usa para clasificar empresas: grandes, medianas o chicas.",
    why: "Las empresas más grandes suelen ser más estables; las chicas pueden crecer más, con más riesgo.",
    aliases: ["capitalización", "market cap", "cap bursátil"],
  },
  {
    id: "per-forward",
    term: "PER estimado",
    category: "Acciones y CEDEARs",
    short: "PER calculado con la ganancia que los analistas esperan para los próximos 12 meses.",
    read: "Si es más bajo que el PER actual, el mercado espera que la ganancia crezca.",
    why: "Mira hacia adelante, pero depende de estimaciones que pueden fallar.",
    aliases: ["forward pe", "per forward", "per proyectado"],
  },
  {
    id: "pb",
    term: "Precio / valor libro",
    category: "Acciones y CEDEARs",
    short: "Compara el precio de la acción con el patrimonio contable de la empresa por acción.",
    read: "1 significa que la bolsa la valúa igual que su patrimonio. Menos de 1, por debajo de lo que dicen sus libros.",
    why: "Es muy usado en bancos y empresas con muchos activos. En empresas de tecnología suele ser alto porque su valor no está en activos físicos.",
    aliases: ["p/b", "p/vl", "price to book", "valor libro"],
  },
  {
    id: "ps",
    term: "Precio / ventas",
    category: "Acciones y CEDEARs",
    short: "Capitalización de la empresa dividida por lo que vende en un año.",
    read: "Un P/S de 3 significa que la empresa vale en bolsa tres años de ventas.",
    why: "Sirve cuando la empresa todavía no gana plata y el PER no se puede usar.",
    aliases: ["p/s", "price to sales"],
  },
  {
    id: "ev-ebitda",
    term: "EV / EBITDA",
    category: "Acciones y CEDEARs",
    short: "Valor total de la empresa (acciones más deuda neta) dividido por su ganancia operativa antes de amortizaciones.",
    read: "Más bajo, más barata la empresa respecto de lo que genera su operación. Se compara dentro del mismo rubro.",
    why: "A diferencia del PER, tiene en cuenta la deuda: dos empresas con igual PER pueden estar muy distintas si una está muy endeudada.",
    aliases: ["ebitda", "enterprise value", "ev"],
  },
  {
    id: "roe",
    term: "ROE",
    category: "Acciones y CEDEARs",
    short: "Ganancia anual como porcentaje del patrimonio de los accionistas.",
    read: "Un ROE de 15 % significa que por cada 100 que pusieron los accionistas, la empresa ganó 15 en el año.",
    why: "Mide qué tan bien usa la empresa el capital de sus dueños. Un ROE muy alto puede venir de mucha deuda.",
    aliases: ["return on equity", "rentabilidad sobre patrimonio"],
  },
  {
    id: "roa",
    term: "ROA",
    category: "Acciones y CEDEARs",
    short: "Ganancia anual como porcentaje de todos los activos de la empresa.",
    read: "En bancos un ROA de 1 % a 2 % es habitual; en industrias, mayor.",
    why: "Muestra la rentabilidad sin el efecto de la deuda.",
    aliases: ["return on assets", "rentabilidad sobre activos"],
  },
  {
    id: "margenes",
    term: "Márgenes",
    category: "Acciones y CEDEARs",
    short: "Qué parte de cada 100 vendidos queda como ganancia en cada etapa.",
    read: "Bruto: después del costo de lo vendido. Operativo: después de los gastos del negocio. Neto: después de intereses e impuestos.",
    why: "Márgenes altos y estables suelen indicar un negocio con ventajas sobre la competencia. Se comparan dentro del mismo rubro.",
    aliases: ["margen bruto", "margen operativo", "margen neto", "rentabilidad"],
  },
  {
    id: "crecimiento",
    term: "Crecimiento",
    category: "Acciones y CEDEARs",
    short: "Cuánto aumentaron las ventas o las ganancias contra un período anterior.",
    read: "+20 % en ventas significa que vendió 20 % más que el año anterior. En empresas argentinas los números en pesos están inflados por la inflación.",
    why: "El precio de una acción depende mucho de lo que se espera que crezca. Un crecimiento que se frena suele castigar el precio.",
    aliases: ["crecimiento de ventas", "growth"],
  },
  {
    id: "deuda-patrimonio",
    term: "Deuda / patrimonio",
    category: "Acciones y CEDEARs",
    short: "Cuánto debe la empresa por cada peso de patrimonio de sus accionistas.",
    read: "0,5 significa que debe la mitad de lo que vale su patrimonio. Más de 1, debe más que su patrimonio.",
    why: "Mucha deuda amplifica las ganancias en los buenos tiempos y las pérdidas en los malos. En bancos se lee distinto porque su negocio es tomar y prestar.",
    aliases: ["apalancamiento", "debt to equity", "endeudamiento"],
  },
  {
    id: "liquidez-corriente",
    term: "Liquidez corriente",
    category: "Acciones y CEDEARs",
    short: "Activos que se convierten en efectivo en menos de un año divididos por las deudas que vencen en ese plazo.",
    read: "Más de 1: la empresa tiene con qué pagar lo que vence en el año. Menos de 1: depende de generar o conseguir fondos.",
    why: "Anticipa problemas de caja de corto plazo.",
    aliases: ["current ratio", "liquidez"],
  },
  {
    id: "cobertura-intereses",
    term: "Cobertura de intereses",
    category: "Acciones y CEDEARs",
    short: "Cuántas veces la ganancia operativa cubre los intereses de la deuda.",
    read: "5 significa que gana cinco veces lo que paga de intereses. Debajo de 2 la deuda pesa mucho.",
    why: "Indica si la empresa puede sostener su deuda.",
    aliases: ["interest coverage"],
  },
  {
    id: "payout",
    term: "Payout",
    category: "Acciones y CEDEARs",
    short: "Porcentaje de la ganancia que la empresa reparte como dividendo.",
    read: "40 % significa que reparte 40 de cada 100 que gana y reinvierte el resto.",
    why: "Un payout cerca o por encima de 100 % puede ser difícil de sostener.",
    aliases: ["payout ratio", "reparto de dividendos"],
  },
  {
    id: "adr",
    term: "ADR",
    category: "Acciones y CEDEARs",
    short: "Certificado que permite operar en Nueva York acciones de una empresa extranjera, por ejemplo Galicia (GGAL) o YPF.",
    read: "Cada ADR representa una cantidad fija de acciones locales y cotiza en dólares.",
    why: "Los ratios de la empresa (PER, ROE, márgenes) son los mismos en el ADR y en la acción local.",
    aliases: ["american depositary receipt"],
  },
  {
    id: "consenso",
    term: "Consenso de analistas",
    category: "Mercado",
    short: "Resumen de lo que recomiendan los analistas que siguen a la empresa: comprar, mantener o vender.",
    read: "Es un conteo de opiniones del último mes, no una garantía.",
    why: "Muestra qué piensa el mercado profesional, pero los analistas también se equivocan y suelen ser optimistas.",
    aliases: ["recomendaciones", "analistas", "rating"],
  },
  {
    id: "sorpresa",
    term: "Sorpresa de resultados",
    category: "Mercado",
    short: "Diferencia entre la ganancia por acción que informó la empresa y la que esperaban los analistas.",
    read: "+5 % significa que ganó 5 % más de lo esperado.",
    why: "El precio suele reaccionar más a la sorpresa que al número en sí.",
    aliases: ["earnings", "balance trimestral", "resultados"],
  },
  {
    id: "comparables",
    term: "Comparables",
    category: "Mercado",
    short: "Empresas del mismo rubro contra las que tiene sentido comparar ratios.",
    read: "La mediana de los comparables es el valor del medio del grupo, sin que lo distorsione un caso extremo.",
    why: "Un PER de 30 puede ser caro para un banco y normal para una tecnológica: el número solo tiene sentido frente a sus pares.",
    aliases: ["peers", "pares", "competidores"],
  },
  {
    id: "tir",
    term: "TIR",
    category: "Renta fija",
    short: "Rendimiento anual que obtenés si comprás el bono hoy y lo mantenés hasta el vencimiento cobrando todos los pagos.",
    read: "Si el precio baja, la TIR sube, y al revés. Una TIR en dólares de 12 % anual significa 12 % por año en esa moneda, si el emisor paga.",
    why: "Permite comparar bonos de distinto precio, cupón y plazo en una sola cifra.",
    aliases: ["tasa interna de retorno", "yield to maturity", "ytm"],
  },
  {
    id: "paridad",
    term: "Paridad",
    category: "Renta fija",
    short: "Precio del bono dividido por su valor técnico.",
    read: "Paridad de 80 % dice que el bono cotiza 20 % por debajo de lo que valdría con capital más intereses devengados.",
    why: "Una paridad baja indica que el mercado ve riesgo o exige más rendimiento.",
    aliases: ["paridad bono"],
  },
  {
    id: "valor-tecnico",
    term: "Valor técnico",
    category: "Renta fija",
    short: "Capital pendiente de un bono más los intereses ya devengados y no cobrados.",
    read: "Es el valor de referencia contra el que se mide la paridad.",
    why: "Es lo que el emisor le debería a quien tiene el bono hoy, sin descuentos.",
    aliases: ["vt"],
  },
  {
    id: "duration",
    term: "Duration",
    category: "Renta fija",
    short: "Plazo promedio, en años, en que recuperás tu inversión, y qué tan sensible es el precio a la tasa.",
    read: "Duration 4 significa que si la tasa sube 1 punto, el precio cae cerca de 4 %.",
    why: "Mide el riesgo de tasa: cuanto más larga, más se mueve el precio.",
    aliases: ["duración", "duration modificada"],
  },
  {
    id: "cupon",
    term: "Cupón",
    category: "Renta fija",
    short: "Interés que paga el bono, normalmente cada seis meses.",
    read: "Se indica como porcentaje anual sobre el capital.",
    why: "Define cuánta plata cobrás por período, además del capital al vencimiento.",
    aliases: ["cupones", "interés"],
  },
  {
    id: "amortizacion",
    term: "Amortización",
    category: "Renta fija",
    short: "Devolución del capital prestado, en una cuota o en varias.",
    read: "En un bono con amortización escalonada, parte del capital se devuelve antes del vencimiento.",
    why: "Reduce el capital pendiente y los intereses futuros.",
    aliases: ["amortizaciones"],
  },
  {
    id: "ley",
    term: "Ley de emisión",
    category: "Renta fija",
    short: "Legislación bajo la cual se emitió el bono: local (Argentina) o Nueva York.",
    read: "Ley Nueva York da, en general, más protección legal ante un incumplimiento.",
    why: "Afecta el precio y las condiciones de una eventual reestructuración.",
    aliases: ["ley local", "ley nueva york"],
  },
  {
    id: "riesgo-pais",
    term: "Riesgo país",
    category: "Mercado",
    short: "Diferencia de rendimiento entre los bonos argentinos y los del Tesoro de EE.UU., en puntos básicos.",
    read: "700 puntos significa que Argentina paga 7 puntos porcentuales más de tasa que EE.UU.",
    why: "Cuanto más alto, más desconfianza del mercado y más caro financiarse.",
    aliases: ["embi", "spread"],
  },
  {
    id: "merval",
    term: "Merval",
    category: "Mercado",
    short: "Índice que sigue a las principales acciones que cotizan en Argentina.",
    read: "Sube o baja según el precio de sus componentes, en pesos.",
    why: "Resume cómo le va a la bolsa local, aunque la inflación y el dólar distorsionan su lectura en pesos.",
    aliases: ["s&p merval", "índice"],
  },
  {
    id: "mep",
    term: "Dólar MEP",
    category: "Dólar",
    short: "Dólar que se consigue comprando un bono en pesos y vendiéndolo en dólares, en la misma cuenta local.",
    read: "Se calcula con el precio de un bono en pesos dividido por el mismo bono en dólares (por ejemplo AL30 ÷ AL30D).",
    why: "Es un dólar legal y accesible, de referencia para valuar inversiones.",
    aliases: ["mep", "dólar bolsa"],
  },
  {
    id: "ccl",
    term: "Dólar CCL",
    category: "Dólar",
    short: "Contado con liquidación: dólar que queda disponible en el exterior.",
    read: "Se calcula igual que el MEP, pero con el bono en dólares cable (por ejemplo AL30 ÷ AL30C).",
    why: "Sirve de referencia para CEDEARs y para ver la brecha con el MEP.",
    aliases: ["ccl", "contado con liqui", "liqui"],
  },
  {
    id: "brecha",
    term: "Brecha",
    category: "Dólar",
    short: "Diferencia porcentual entre dos cotizaciones del mismo activo o del dólar.",
    read: "Una brecha de 5 % entre CCL implícito y CCL de referencia indica que el CEDEAR está 5 % más caro de lo que debería.",
    why: "Ayuda a detectar si un CEDEAR cotiza con prima o con descuento.",
    aliases: ["prima", "descuento"],
  },
  {
    id: "variacion",
    term: "Variación",
    category: "Mercado",
    short: "Cuánto cambió el precio respecto del cierre anterior, en monto y en porcentaje.",
    read: "Verde es suba y rojo es baja. +2 % es que hoy vale 2 % más que ayer al cierre.",
    why: "Muestra el movimiento del día, pero un día solo no dice mucho sobre la tendencia.",
    aliases: ["cambio", "variación diaria"],
  },
  {
    id: "volumen",
    term: "Volumen",
    category: "Mercado",
    short: "Cantidad (o monto) operado en el día.",
    read: "Un volumen muy superior al habitual indica interés inusual en el activo.",
    why: "Un movimiento de precio con mucho volumen suele ser más confiable que uno con poco. Con poco volumen cuesta comprar y vender.",
    aliases: ["liquidez", "operado"],
  },
  {
    id: "apertura-cierre",
    term: "Apertura y cierre anterior",
    category: "Mercado",
    short: "Apertura: primer precio del día. Cierre anterior: último precio de la rueda previa.",
    read: "Si la apertura está lejos del cierre anterior, hubo un salto (gap) por noticias o por movimientos fuera del horario.",
    why: "La variación del día se mide contra el cierre anterior.",
    aliases: ["apertura", "cierre", "gap"],
  },
  {
    id: "maximo-minimo",
    term: "Máximo y mínimo",
    category: "Mercado",
    short: "El precio más alto y el más bajo del período.",
    read: "El rango entre ambos muestra cuánto se movió el activo en el período.",
    why: "El máximo y el mínimo de 52 semanas dan una idea de dónde está el precio actual dentro de su historia.",
    aliases: ["52 semanas", "rango"],
  },
  {
    id: "velas",
    term: "Gráfico de velas",
    category: "Gráficos",
    short: "Cada vela resume un período con apertura, cierre, máximo y mínimo.",
    read: "El cuerpo va de la apertura al cierre: verde si cerró más arriba, rojo si cerró más abajo. Las mechas marcan el máximo y el mínimo.",
    why: "Muestra en una sola figura cómo se movió el precio dentro de cada período.",
    aliases: ["candlestick", "velas japonesas"],
  },
  {
    id: "media-movil",
    term: "Media móvil",
    category: "Gráficos",
    short: "Promedio del precio de los últimos N períodos, que se recalcula en cada vela.",
    read: "Si el precio está por encima de su media móvil, la tendencia reciente es alcista; por debajo, bajista.",
    why: "Suaviza el ruido y ayuda a ver la tendencia. Llega tarde: confirma movimientos, no los anticipa.",
    aliases: ["sma", "promedio móvil", "mm"],
  },
  {
    id: "rsi",
    term: "RSI",
    category: "Gráficos",
    short: "Indicador de 0 a 100 que mide la fuerza de las subas contra las bajas recientes.",
    read: "Arriba de 70 se suele leer como sobrecompra; debajo de 30, como sobreventa.",
    why: "Puede avisar de un agotamiento, pero en tendencias fuertes se queda mucho tiempo en esos extremos.",
    aliases: ["relative strength index"],
  },
  {
    id: "macd",
    term: "MACD",
    category: "Gráficos",
    short: "Compara dos medias móviles para detectar cambios de impulso.",
    read: "Cuando la línea MACD cruza hacia arriba su señal, el impulso mejora; al cruzar hacia abajo, empeora.",
    why: "Ayuda a ver si una tendencia gana o pierde fuerza.",
    aliases: ["moving average convergence divergence"],
  },
  {
    id: "bollinger",
    term: "Bandas de Bollinger",
    category: "Gráficos",
    short: "Dos bandas alrededor de una media móvil que se ensanchan cuando hay más volatilidad.",
    read: "Tocar la banda superior no es una señal de venta por sí solo: indica que el precio está lejos de su promedio.",
    why: "Sirve para dimensionar qué tan movido está el activo.",
    aliases: ["bandas"],
  },
  {
    id: "alerta",
    term: "Alerta de precio",
    category: "Mercado",
    short: "Aviso que te llega cuando un precio supera o cae por debajo de un valor que elegiste.",
    read: "Elegís el instrumento, la condición (sube por encima / baja por debajo) y el valor objetivo.",
    why: "Evita mirar la pantalla todo el día. La app solo avisa: no opera por vos.",
    aliases: ["alertas", "aviso"],
  },
];

const BY_ID = new Map(GLOSSARY.map((g) => [g.id, g]));

export function glossaryEntry(id: string): GlossaryEntry | undefined {
  return BY_ID.get(id);
}
